name: Dialyzer

on: push

jobs:
  Dialyzer:
    runs-on: ubuntu-latest

    container:
      image: mikaak/elixir:1.13-alpine
      env:
        MIX_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Install Rebar & Hex
        run: mix local.hex --force && mix local.rebar --force

      - name: Install Tar
        run: apk add --no-cache tar

      - name: Cache Deps & Build
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-mix-dialyzer-${{ hashFiles('**/mix.lock') }}
          path: |
            deps
            _build
            dialyzer
            !._build/dev/lib/error_message/
          restore-keys: |
            ${{ runner.os }}-mix-dialyzer-

      - name: Install Dependencies
        run: mix deps.get

      - name: Compile Project
        run: mix compile

      - name: Run Dialyzer
        run: mix dialyzer


