name: Test

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest

    container:
      image: mikaak/elixir:1.12-alpine
      env:
        MIX_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Install Rebar & Hex
        run: mix local.hex --force && mix local.rebar --force
        working-directory: ./error_message

      - name: Install Tar
        run: apk add --no-cache tar

      - name: Cache Deps & Build
        uses: actions/cache@v2
        with:
          key: ${{github.ref}}-deps-build-cache
          path: |
            ./error_message/deps
            ./error_message/_build
            !./error_message/_build/dev/lib/error_message/
     - name: Install Dependencies
        run: mix deps.get
        working-directory: ./error_message

      - name: Compile Project
        run: mix compile
        working-directory: ./error_message

      - name: Run Tests
        run: mix test
        working-directory: ./error_message
